### PR TITLE
test: fix Shopify tests

### PR DESCRIPTION
**Pull request by Alchez**
image

### CODE REVIEW

**Comment by vjFaLk** [comment]
@Alchez where are these test json data files from?

**Comment by Alchez** [comment]
> @Alchez where are these test json data files from?

I imported them from ERPNext, but it seems like they created some test items somewhere and then changed any PII. None of the values actually link or refer to anything.

**Comment by vjFaLk** [comment]
@Alchez deepsource fixes would be `style` not `ci`. CI scope is used when something related to the CI changes.

**Comment by Alchez** [comment]
> @Alchez deepsource fixes would be `style` not `ci`. CI scope is used when something related to the CI changes.

Ah gotcha

**Pull request merged**
